package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.AwsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.S3Storage
import jetbrains.buildServer.configs.kotlin.projectFeatures.awsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.s3Storage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<AwsConnection> {
            awsConnection {
                id = "AwsConnectionUsesSakura_AmazonWebServicesAws"
                name = "Amazon Web Services (AWS)"
                regionName = "eu-west-1"
                credentialsType = static {
                    accessKeyId = "AKIA5JH2VERVJFGDHSDZ"
                    secretAccessKey = "credentialsJSON:5eb86222-6fe6-4757-99f0-d5b683d9dc2f"
                    stsEndpoint = "https://sts.eu-west-1.amazonaws.com"
                }
                allowInBuilds = false
            }
        }
        feature1.apply {
            allowInSubProjects = true
            allowInBuilds = true
            param("awsSessionDuration", "")
        }
        val feature2 = find<S3Storage> {
            s3Storage {
                id = "PROJECT_EXT_9"
                bucketName = "ollven-test"
                forceVirtualHostAddressing = true
                awsEnvironment = default {
                    awsRegionName = "eu-west-1"
                }
                connectionId = "AwsConnectionUsesSakura_AmazonWebServicesAws"
            }
        }
        feature2.apply {
        }
    }
}
